/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 25-Feb-2020 19:18:33
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 21
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
const int BL = 21;
const double B[21] = {
     0.0241774250139,  0.02021685035891,  0.02741091868321,  0.03517776353965,
    0.04315459870005,  0.05092661205551,  0.05805802846835,  0.06412682971124,
    0.06875978231095,  0.07166428639988,   0.0726538095167,  0.07166428639988,
    0.06875978231095,  0.06412682971124,  0.05805802846835,  0.05092661205551,
    0.04315459870005,  0.03517776353965,  0.02741091868321,  0.02021685035891,
     0.0241774250139
};
